services:
  retina-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env # This will override the environment variables defined in the Dockerfile
    volumes:
      - ./retina_data:/app/retina_data
    restart: unless-stopped
    # Environment variables can also be set directly here if needed
    environment:
      - ENVIRONMENT=production
      - PORT=8000
